/*
 * Created by RadenMas on 14/3/2022.
 * Copyright (c) 2022.
 */

package com.radenmas.smart.water.meter.utils

/**
 * Created by RadenMas on 14/03/2022.
 */
object Constant {
    const val app_name = "Smart Water Meter"
    const val app_pref = "app_pref"
    const val level_user = "levelUser"
    const val dev_name = "M Sukron Kurniawan"
    const val login = "Masuk"
    const val login_desc = "Lorem ipsum dolor sit amet"
    const val username = "Username"
    const val password = "Kata Sandi"
    const val forgot_password = "Lupa kata sandi?"
    const val user = "Pelanggan"
    const val admin = "Pengelola"
    const val full_name = "Nama Lengkap"
    const val tagihan = "Tagihan"
    const val rp = "Rp."
    const val pemakaian_air = "Pemakaian Air"
    const val statistik = "Statistik"
    const val skip = "Lewati"
    const val m3 = "m3"
    const val pembayaran = "Riwayat Pembayaran"
    const val view_all = "Lihat semua"
    const val user_id = "ID Pelanggan"
    const val phone_number = "Nomor HP"
    const val alamat = "Alamat"
    const val akun = "Akun"
    const val ubah_profil = "Ubah Profil"
    const val tentang = "Tentang"
    const val guide = "Panduan"
    const val terms = "Syarat dan Ketentuan"
    const val privacy = "Kebijakan Privasi"
    const val help = "Pusat Bantuan"
    const val logout = "Keluar"
    const val profile = "Profil"
    const val webserver = "Webserver"
    const val notification = "Notifikasi"
    const val debit = "Debit Air"
    const val save = "Simpan"
    const val pengaduan = "Pengaduan"
    const val jenis_pengaduan = "Jenis Pengaduan"
    const val deskripsi = "Deskripsi"
    const val send = "Kirim"
    const val keluhan = "Keluhan"
    const val riwayat = "Riwayat"
    const val pdam = "PDAM"
    const val sambungan = "Sambungan"
    const val setting = "Pengaturan"
    const val add_user = "Tambah Pelanggan"
    const val add = "Tambah"
    const val data_user = "Data Pelanggan"
    const val hai = "Hai,"
    const val dash = "-"
    const val confirm = "Konfirmasi"
    const val desc_logout = "Apakah Anda yakin ingin keluar dari aplikasi ini?"
    const val no = "Tidak"
    const val yes = "Ya"
    const val sent = "Terkirim"
    const val processed = "Diproses"
    const val finish = "Selesai"
    const val rejected = "Ditolak"
    const val paid_off = "Lunas"
    const val not_yet_paid_off = "Belum Lunas"
    const val pattern_input_date = "yyyy-MM-dd"
    const val pattern_output_date = "dd MMM yyyy"

    const val color_primary = "#0091FF"
    const val color_primary_dark = "#033FC0"
    const val color_primary_light = "#9ED0F6"
    const val color_primary_light2 = "#BFE3FF"
    const val color_primary_text = "#212226"
    const val color_secondary_text = "#757575"
    const val color_white_text = "#F7F9FC"
    const val color_divider = "#BDBDBD"
    const val color_hint = "#C4C4C4"
    const val color_black = "#000000"
    const val color_white = "#FFFFFF"
    const val color_red = "#E02020"
    const val color_semi_red = "#26E02020"
    const val color_green = "#15BE6D"
    const val color_semi_green = "#2615DF7E"
    const val color_orange = "#FFAB00"
    const val color_semi_orange = "#26FFAB00"
    const val color_semi_blue = "#260091FF"
}